Repository codehaus-plexus/plexus-xml, pull requests merged in 2024-05, with the labels that each got.

#30 Bump parent to 17 and updates
  pom.xml
Labels: dependencies

#31 Switch to Junit 5
  pom.xml
  src/test/java/org/codehaus/plexus/util/xml/PrettyPrintXMLWriterTest.java
  src/test/java/org/codehaus/plexus/util/xml/XmlStreamReaderTest.java
  src/test/java/org/codehaus/plexus/util/xml/XmlStreamWriterTest.java
  src/test/java/org/codehaus/plexus/util/xml/XmlUtilTest.java
  src/test/java/org/codehaus/plexus/util/xml/XmlWriterUtilTest.java
  src/test/java/org/codehaus/plexus/util/xml/Xpp3DomBuilderTest.java
  src/test/java/org/codehaus/plexus/util/xml/Xpp3DomTest.java
  src/test/java/org/codehaus/plexus/util/xml/Xpp3DomUtilsTest.java
  src/test/java/org/codehaus/plexus/util/xml/Xpp3DomWriterTest.java
  src/test/java/org/codehaus/plexus/util/xml/pull/IBMXML10Tests_Test_IBMXMLConformanceTestSuite_not_wftests_Test_IBMXMLConformanceTestSuite_Production24_Test.java
  src/test/java/org/codehaus/plexus/util/xml/pull/IBMXML10Tests_Test_IBMXMLConformanceTestSuite_not_wftests_Test_IBMXMLConformanceTestSuite_Production2_Test.java
  src/test/java/org/codehaus/plexus/util/xml/pull/IBMXML10Tests_Test_IBMXMLConformanceTestSuite_not_wftests_Test_IBMXMLConformanceTestSuite_Production32_Test.java
  src/test/java/org/codehaus/plexus/util/xml/pull/IBMXML10Tests_Test_IBMXMLConformanceTestSuite_not_wftests_Test_IBMXMLConformanceTestSuite_Production66_Test.java
  src/test/java/org/codehaus/plexus/util/xml/pull/IBMXML10Tests_Test_IBMXMLConformanceTestSuite_not_wftests_Test_IBMXMLConformanceTestSuite_Production80_Test.java
  src/test/java/org/codehaus/plexus/util/xml/pull/MXParserTest.java
  src/test/java/org/codehaus/plexus/util/xml/pull/eduni_misc_Test_BjoernHoehrmannviaHST2013_09_18_Test.java
Labels: maintenance

#32 Remove special chars from xml output
  src/main/java/org/codehaus/plexus/util/xml/PrettyPrintXMLWriter.java
  src/main/java/org/codehaus/plexus/util/xml/pull/MXSerializer.java
  src/test/java/org/codehaus/plexus/util/xml/Xpp3DomWriterTest.java
  src/test/java/org/codehaus/plexus/util/xml/pull/MXSerializerTest.java
Labels: bug

#38 Deploy snapshots for 3.x branch
  .github/workflows/maven.yml
Labels: build

#29 Allow nulls for write elements in MXSerializer
  src/main/java/org/codehaus/plexus/util/xml/pull/MXSerializer.java
  src/test/java/org/codehaus/plexus/util/xml/pull/MXSerializerTest.java
Labels: bug

#41 Allow nulls for write elements in MXSerializer
  src/main/java/org/codehaus/plexus/util/xml/pull/MXSerializer.java
  src/test/java/org/codehaus/plexus/util/xml/pull/MXSerializerTest.java
Labels: bug
